/* ──────────────────────────────────────────────────────────────
   Yellowstone attractions
   res:  'none' = walk up  ·  'rec' = plan/arrive early  ·  'req' = book ahead
   hours: midpoint of the stated range, used for schedule totals
   ────────────────────────────────────────────────────────────── */

const REGIONS = [
    { key: 'geyser',  label: 'Old Faithful & Upper Basin' },
    { key: 'midway',  label: 'Midway & Lower Basin' },
    { key: 'norris',  label: 'Madison, Gibbon & Norris' },
    { key: 'mammoth', label: 'Mammoth & North' },
    { key: 'tower',   label: 'Tower–Roosevelt & Lamar' },
    { key: 'canyon',  label: 'Canyon & Hayden Valley' },
    { key: 'lake',    label: 'Lake & West Thumb' },
    { key: 'teton',   label: 'Grand Teton NP' },
    { key: 'gateway', label: 'Gateway Towns' },
    { key: 'airport', label: 'Airports & Access' },
];

const ATTRACTIONS = [

    /* ── Old Faithful & Upper Geyser Basin ─────────────────── */
    {
        id: 'old-faithful', name: 'Old Faithful Geyser', region: 'geyser',
        lat: 44.4605, lng: -110.8281,
        what: "The park's signature cone geyser, throwing 100–180 ft of water about every 90 minutes.",
        time: '45–60 min', hours: 1, res: 'none',
        resNote: 'Predicted eruption times are posted at the visitor center and in the NPS app.',
    },
    {
        id: 'upper-geyser-basin', name: 'Upper Geyser Basin Loop', region: 'geyser',
        lat: 44.4640, lng: -110.8380,
        what: 'The densest concentration of active geysers on Earth — Castle, Grand, Riverside and Daisy on one boardwalk loop.',
        time: '2–3 hrs', hours: 2.5, res: 'none',
        resNote: 'Free-flowing boardwalk; check the day\'s geyser predictions before you set off.',
    },
    {
        id: 'morning-glory', name: 'Morning Glory Pool', region: 'geyser',
        lat: 44.4652, lng: -110.8397,
        what: 'Deep-blue hot spring at the far end of the Upper Basin boardwalk, best reached on foot or by rented bike.',
        time: '1.5 hrs round trip', hours: 1.5, res: 'none',
        resNote: 'No reservation; bike rental at Old Faithful is first-come.',
    },
    {
        id: 'old-faithful-inn', name: 'Old Faithful Inn', region: 'geyser',
        lat: 44.4597, lng: -110.8306,
        what: '1904 log "parkitecture" lodge with a seven-storey lobby and a second-floor deck over the geyser.',
        time: '30–45 min', hours: 0.75, res: 'req',
        resNote: 'Free to walk through. Dining Room dinner requires a reservation — book weeks ahead.',
    },
    {
        id: 'black-sand-basin', name: 'Black Sand Basin', region: 'geyser',
        lat: 44.4665, lng: -110.8390,
        what: 'Compact basin holding Emerald Pool, Sunset Lake and Cliff Geyser, a few steps from the road.',
        time: '30–40 min', hours: 0.6, res: 'none',
        resNote: 'Small lot — easy to slot in on the way past.',
    },
    {
        id: 'biscuit-basin', name: 'Biscuit Basin & Mystic Falls', region: 'geyser',
        lat: 44.4870, lng: -110.8550,
        what: 'Sapphire Pool and a 2.4-mi trail to a 70-ft falls on the Little Firehole River.',
        time: '45 min basin / 2.5 hrs with falls', hours: 2.5, res: 'none',
        status: 'closed',
        statusNote: 'Closed since the July 2024 hydrothermal explosion — confirm on the NPS park-conditions page before you plan around it.',
        resNote: 'No reservation, but access has been closed — verify first.',
    },
    {
        id: 'lone-star', name: 'Lone Star Geyser', region: 'geyser',
        lat: 44.4139, lng: -110.8058,
        what: 'Flat 4.8-mi round trip on an old service road to a solitary 12-ft cone that erupts roughly every 3 hours.',
        time: '3–4 hrs', hours: 3.5, res: 'none',
        resNote: 'Bikes allowed to the geyser — halves the time.',
    },

    /* ── Midway & Lower Geyser Basin ───────────────────────── */
    {
        id: 'grand-prismatic', name: 'Grand Prismatic Spring', region: 'midway',
        lat: 44.5251, lng: -110.8382,
        what: 'The largest hot spring in the United States — 370 ft across, ringed by orange and green microbial mats.',
        time: '45 min', hours: 0.75, res: 'rec',
        resNote: 'No booking, but the Midway lot fills solid by 9am — go early or after 5pm.',
    },
    {
        id: 'prismatic-overlook', name: 'Grand Prismatic Overlook', region: 'midway',
        lat: 44.5124, lng: -110.8339,
        what: 'Short uphill spur from the Fairy Falls trailhead to the platform where the spring\'s full colour rings are visible.',
        time: '1–1.5 hrs', hours: 1.25, res: 'rec',
        resNote: 'No booking; the trailhead lot is small and fills mid-morning.',
    },
    {
        id: 'fairy-falls', name: 'Fairy Falls', region: 'midway',
        lat: 44.5312, lng: -110.8735,
        what: '200-ft plunge waterfall on a level 5.4-mi round trip from the same trailhead as the overlook.',
        time: '2.5–3 hrs', hours: 2.75, res: 'none',
        resNote: 'Pair it with the overlook — same parking, same trail start.',
    },
    {
        id: 'fountain-paint-pot', name: 'Fountain Paint Pot', region: 'midway',
        lat: 44.5510, lng: -110.8080,
        what: 'Half-mile boardwalk that hits all four hydrothermal types — geyser, hot spring, mudpot and fumarole.',
        time: '45 min', hours: 0.75, res: 'none',
        resNote: 'The best single stop for understanding what you are looking at.',
    },
    {
        id: 'firehole-lake-drive', name: 'Firehole Lake Drive', region: 'midway',
        lat: 44.5545, lng: -110.8005,
        what: 'One-way 3-mi loop past Great Fountain Geyser and White Dome, both visible from the car.',
        time: '30–45 min', hours: 0.6, res: 'none',
        resNote: 'Great Fountain eruption windows are posted at the entrance to the drive.',
    },
    {
        id: 'firehole-canyon', name: 'Firehole Canyon Drive & Falls', region: 'midway',
        lat: 44.6260, lng: -110.8620,
        what: 'One-way canyon road under dark rhyolite cliffs to a 40-ft waterfall and a summer swimming hole.',
        time: '30 min', hours: 0.5, res: 'none',
        resNote: 'Swim area opens only when river levels drop, usually mid-July.',
    },

    /* ── Madison, Gibbon & Norris ──────────────────────────── */
    {
        id: 'norris', name: 'Norris Geyser Basin', region: 'norris',
        lat: 44.7263, lng: -110.7031,
        what: 'The hottest and most volatile basin in the park, and home to Steamboat, the tallest active geyser in the world.',
        time: '1.5–2 hrs', hours: 1.75, res: 'none',
        resNote: 'Two loops — Porcelain (short, open) and Back Basin (longer, forested).',
    },
    {
        id: 'artists-paintpots', name: "Artists' Paintpots", region: 'norris',
        lat: 44.6910, lng: -110.7400,
        what: '1.2-mi loop climbing past bubbling pink mudpots and blue springs on a burned hillside.',
        time: '45 min–1 hr', hours: 0.9, res: 'none',
        resNote: 'Mudpots are thickest and loudest in late summer.',
    },
    {
        id: 'gibbon-falls', name: 'Gibbon Falls', region: 'norris',
        lat: 44.6538, lng: -110.7720,
        what: '84-ft falls spilling over the rim of the Yellowstone caldera, seen from a paved roadside walkway.',
        time: '15–20 min', hours: 0.3, res: 'none',
        resNote: 'Quick stop on the Madison–Norris leg.',
    },
    {
        id: 'virginia-cascade', name: 'Virginia Cascade', region: 'norris',
        lat: 44.7130, lng: -110.6510,
        what: 'Narrow one-way drive along the Gibbon River to a 60-ft cascade most people skip.',
        time: '20 min', hours: 0.35, res: 'none',
        resNote: 'Not suitable for large RVs or trailers.',
    },
    {
        id: 'roaring-mountain', name: 'Roaring Mountain', region: 'norris',
        lat: 44.7768, lng: -110.7307,
        what: 'A bleached hillside of hissing fumaroles — loudest and steamiest in cold morning air.',
        time: '10–15 min', hours: 0.25, res: 'none',
        resNote: 'Roadside pullout; best before 9am.',
    },
    {
        id: 'monument-geyser', name: 'Monument Geyser Basin', region: 'norris',
        lat: 44.6790, lng: -110.7530,
        what: 'Steep 2-mi round trip to a ridge of strange chimney-like sinter cones above the Gibbon.',
        time: '1.5–2 hrs', hours: 1.75, res: 'none',
        resNote: 'Sharp 500-ft climb in the last half mile.',
    },

    /* ── Mammoth & North ───────────────────────────────────── */
    {
        id: 'mammoth-terraces', name: 'Mammoth Hot Springs Terraces', region: 'mammoth',
        lat: 44.9766, lng: -110.7027,
        what: 'Travertine terraces built layer by layer by hot spring water — an upper terrace drive plus lower boardwalks.',
        time: '1.5–2 hrs', hours: 1.75, res: 'none',
        resNote: 'Do the Upper Terrace Drive first, then walk down through the Lower Terraces.',
    },
    {
        id: 'fort-yellowstone', name: 'Fort Yellowstone & Albright Center', region: 'mammoth',
        lat: 44.9764, lng: -110.6975,
        what: 'Historic US Cavalry post that ran the park before the NPS existed, with the main north-side visitor centre.',
        time: '45 min', hours: 0.75, res: 'none',
        resNote: 'Backcountry permits and fishing licences are issued here.',
    },
    {
        id: 'roosevelt-arch', name: 'Roosevelt Arch', region: 'mammoth',
        lat: 45.0300, lng: -110.7080,
        what: '1903 basalt arch at the North Entrance, inscribed "For the Benefit and Enjoyment of the People."',
        time: '15 min', hours: 0.25, res: 'none',
        resNote: 'Obligatory photo stop if you come through Gardiner.',
    },
    {
        id: 'bunsen-peak', name: 'Bunsen Peak', region: 'mammoth',
        lat: 44.9440, lng: -110.7050,
        what: '4.2-mi round-trip climb up an old volcanic plug to a 360° view over the Gallatin Range.',
        time: '2.5–3.5 hrs', hours: 3, res: 'none',
        resNote: 'Exposed and hot by midday — start early.',
    },
    {
        id: 'wraith-falls', name: 'Wraith Falls', region: 'mammoth',
        lat: 44.9430, lng: -110.6100,
        what: 'Easy 1-mi round trip across sage meadow to a 90-ft cascade — a good first-morning leg stretcher.',
        time: '45 min', hours: 0.75, res: 'none',
        resNote: 'Flat, family-friendly, rarely crowded.',
    },
    {
        id: 'undine-falls', name: 'Undine Falls', region: 'mammoth',
        lat: 44.9440, lng: -110.6300,
        what: 'Three-tiered 60-ft falls on Lava Creek, visible straight from a roadside overlook.',
        time: '10 min', hours: 0.2, res: 'none',
        resNote: 'Two minutes from the car.',
    },
    {
        id: 'sheepeater-cliff', name: 'Sheepeater Cliff', region: 'mammoth',
        lat: 44.8790, lng: -110.7300,
        what: 'Columnar basalt cliff with a riverside picnic area and a resident pika colony in the talus.',
        time: '20–30 min', hours: 0.4, res: 'none',
        resNote: 'Good lunch stop between Mammoth and Norris.',
    },

    /* ── Tower–Roosevelt & Lamar ───────────────────────────── */
    {
        id: 'lamar-valley', name: 'Lamar Valley', region: 'tower',
        lat: 44.8971, lng: -110.2260,
        what: "The park's richest wildlife corridor — wolves, bison herds, grizzlies and pronghorn along the Lamar River.",
        time: '2–4 hrs', hours: 3, res: 'rec',
        resNote: 'No booking, but it only works at dawn or dusk. Bring binoculars or a spotting scope.',
    },
    {
        id: 'slough-creek', name: 'Slough Creek', region: 'tower',
        lat: 44.9270, lng: -110.3100,
        what: 'Gravel spur to the wolf-watchers\' gathering ground and one of the best cutthroat trout streams in the Rockies.',
        time: '1.5–3 hrs', hours: 2, res: 'req',
        resNote: 'Free to visit. A Yellowstone fishing permit is required to fish; campground sites are reserved months ahead.',
    },
    {
        id: 'tower-fall', name: 'Tower Fall', region: 'tower',
        lat: 44.8930, lng: -110.3866,
        what: '132-ft waterfall framed by volcanic pinnacles, seen from a short paved overlook by the general store.',
        time: '20–30 min', hours: 0.4, res: 'none',
        resNote: 'The trail to the base of the falls remains closed.',
    },
    {
        id: 'calcite-springs', name: 'Calcite Springs Overlook', region: 'tower',
        lat: 44.8990, lng: -110.3930,
        what: 'Short boardwalk over the Narrows of the Yellowstone, with sulphur springs steaming out of the riverbank below.',
        time: '20 min', hours: 0.35, res: 'none',
        resNote: 'Bighorn sheep are often on the cliffs opposite.',
    },
    {
        id: 'river-picnic-trail', name: 'Yellowstone River Picnic Area Trail', region: 'tower',
        lat: 44.9260, lng: -110.3900,
        what: '3.7-mi rim walk high above the Narrows — basalt columns, osprey nests and almost no crowds.',
        time: '2–2.5 hrs', hours: 2.25, res: 'none',
        resNote: 'Little shade; carry water.',
    },
    {
        id: 'petrified-tree', name: 'Petrified Tree', region: 'tower',
        lat: 44.9130, lng: -110.4020,
        what: 'A 50-million-year-old redwood trunk turned to stone, still standing upright a few steps from the car park.',
        time: '15 min', hours: 0.25, res: 'none',
        resNote: 'Tight one-way loop — no RVs.',
    },
    {
        id: 'trout-lake', name: 'Trout Lake', region: 'tower',
        lat: 44.9160, lng: -110.1270,
        what: 'Steep half-mile climb to a small mountain lake where spawning cutthroat crowd the inlet in June.',
        time: '1–1.5 hrs', hours: 1.25, res: 'none',
        resNote: 'Otters are regularly seen here; the trailhead pullout holds about ten cars.',
    },
    {
        id: 'blacktail-drive', name: 'Blacktail Plateau Drive', region: 'tower',
        lat: 44.9250, lng: -110.5900,
        what: '6-mi one-way dirt road through aspen and sage — a quiet, slow alternative to the main Mammoth–Tower road.',
        time: '45 min', hours: 0.75, res: 'none',
        resNote: 'Dry conditions only; no trailers.',
    },
    {
        id: 'cookout', name: 'Old West Dinner Cookout', region: 'tower',
        lat: 44.9130, lng: -110.4180,
        what: 'Horseback or covered-wagon ride out to a steak-and-cornbread dinner in Pleasant Valley.',
        time: '3–4 hrs', hours: 3.5, res: 'req',
        resNote: 'Reservation required through Yellowstone National Park Lodges — sells out weeks in advance.',
    },

    /* ── Canyon & Hayden Valley ────────────────────────────── */
    {
        id: 'artist-point', name: 'Artist Point', region: 'canyon',
        lat: 44.7199, lng: -110.4787,
        what: 'The postcard view — the 308-ft Lower Falls framed by the full length of the Grand Canyon of the Yellowstone.',
        time: '30 min', hours: 0.5, res: 'rec',
        resNote: 'No booking; the lot is full 10am–4pm. Best light is early morning.',
    },
    {
        id: 'south-rim-trail', name: 'South Rim Trail', region: 'canyon',
        lat: 44.7180, lng: -110.4890,
        what: 'Rim walk linking Upper Falls, Uncle Tom\'s Overlook and Artist Point along the canyon\'s south side.',
        time: '1.5–2 hrs', hours: 1.75, res: 'none',
        resNote: 'The old Uncle Tom\'s staircase down into the canyon is permanently closed; the overlook above it is open.',
    },
    {
        id: 'brink-lower-falls', name: 'Brink of the Lower Falls', region: 'canyon',
        lat: 44.7180, lng: -110.5000,
        what: 'Switchbacking 0.7-mi round trip down to a platform right at the lip of the 308-ft drop.',
        time: '45 min–1 hr', hours: 0.9, res: 'none',
        resNote: '600-ft climb back out — the steepest short walk in the park.',
    },
    {
        id: 'lookout-point', name: 'Lookout Point & Red Rock Point', region: 'canyon',
        lat: 44.7208, lng: -110.4980,
        what: 'North-rim overlook of the Lower Falls, plus a steep stair descent to a spray-level view.',
        time: '45 min–1 hr', hours: 0.9, res: 'none',
        resNote: 'Red Rock adds about 500 ft of stairs each way.',
    },
    {
        id: 'inspiration-point', name: 'Inspiration Point', region: 'canyon',
        lat: 44.7290, lng: -110.4720,
        what: 'Far-end north-rim viewpoint looking straight down the canyon at its most colourful stretch.',
        time: '20–30 min', hours: 0.4, res: 'none',
        resNote: 'Reached from the one-way North Rim Drive.',
    },
    {
        id: 'mount-washburn', name: 'Mount Washburn', region: 'canyon',
        lat: 44.7960, lng: -110.4340,
        what: '6.4-mi round-trip climb to a 10,243-ft fire lookout with the widest view in Yellowstone.',
        time: '4–5 hrs', hours: 4.5, res: 'none',
        resNote: 'Dunraven Pass road typically opens late May. Afternoon lightning is a real risk — start by 8am.',
    },
    {
        id: 'hayden-valley', name: 'Hayden Valley', region: 'canyon',
        lat: 44.6597, lng: -110.4700,
        what: 'Broad glacial river valley holding the biggest bison herds in the park, with frequent grizzly sightings.',
        time: '1–2 hrs', hours: 1.5, res: 'rec',
        resNote: 'No booking; go at first or last light. Expect bison jams on the road.',
    },
    {
        id: 'mud-volcano', name: "Mud Volcano & Dragon's Mouth", region: 'canyon',
        lat: 44.6249, lng: -110.4340,
        what: 'Acidic, sulphurous mudpots and a cave spring that belches steam and genuinely roars.',
        time: '45 min', hours: 0.75, res: 'none',
        resNote: 'The smelliest stop in Yellowstone — and worth it.',
    },
    {
        id: 'sulphur-caldron', name: 'Sulphur Caldron', region: 'canyon',
        lat: 44.6320, lng: -110.4330,
        what: 'Roadside pullout above one of the most acidic springs in the park, at roughly the pH of battery acid.',
        time: '10 min', hours: 0.2, res: 'none',
        resNote: 'Directly across the road from Mud Volcano.',
    },

    /* ── Lake & West Thumb ─────────────────────────────────── */
    {
        id: 'west-thumb', name: 'West Thumb Geyser Basin', region: 'lake',
        lat: 44.4166, lng: -110.5730,
        what: 'Hot springs and the famous Fishing Cone spilling straight into the edge of Yellowstone Lake.',
        time: '45 min–1 hr', hours: 0.9, res: 'none',
        resNote: 'Best light in the evening, looking east across the lake.',
    },
    {
        id: 'lake-boat-tour', name: 'Yellowstone Lake Scenicruiser', region: 'lake',
        lat: 44.5350, lng: -110.4380,
        what: 'One-hour narrated boat tour out of Bridge Bay Marina on the largest high-elevation lake in North America.',
        time: '1.5 hrs incl. check-in', hours: 1.5, res: 'req',
        resNote: 'Reservation required — book through Yellowstone National Park Lodges; limited daily departures.',
    },
    {
        id: 'lake-hotel', name: 'Lake Yellowstone Hotel', region: 'lake',
        lat: 44.5510, lng: -110.4000,
        what: '1891 colonial-revival hotel with a sunroom of windows looking straight down the lake.',
        time: '30–45 min', hours: 0.75, res: 'req',
        resNote: 'Free to walk through and sit in the sunroom. Dining Room requires a reservation.',
    },
    {
        id: 'storm-point', name: 'Storm Point Trail', region: 'lake',
        lat: 44.5450, lng: -110.3300,
        what: 'Flat 2.3-mi loop through forest and meadow to a windswept lakeshore point with a marmot colony.',
        time: '1.5 hrs', hours: 1.5, res: 'none',
        resNote: 'Frequently closed in early summer for bear activity — check the trailhead sign.',
    },
    {
        id: 'natural-bridge', name: 'Natural Bridge', region: 'lake',
        lat: 44.5410, lng: -110.4270,
        what: 'Easy 3-mi round trip, bike-friendly, to a 51-ft rhyolite arch cut through by Bridge Creek.',
        time: '1.5 hrs', hours: 1.5, res: 'none',
        resNote: 'Often closed early summer for bears feeding on spawning trout.',
    },
    {
        id: 'fishing-bridge', name: 'Fishing Bridge & LeHardys Rapids', region: 'lake',
        lat: 44.5650, lng: -110.3730,
        what: 'Historic bridge over the lake outlet, plus rapids a few miles north where cutthroat leap upstream in June.',
        time: '30–45 min', hours: 0.6, res: 'none',
        resNote: 'Fishing from the bridge itself has been banned since 1973.',
    },
    {
        id: 'elephant-back', name: 'Elephant Back Mountain', region: 'lake',
        lat: 44.5540, lng: -110.3960,
        what: '3.6-mi forested loop climbing 800 ft to an overlook of Yellowstone Lake and the Absaroka Range.',
        time: '2 hrs', hours: 2, res: 'none',
        resNote: 'Steady climb, no views until the top.',
    },
    {
        id: 'grant-lewis-falls', name: 'Grant Village & Lewis Falls', region: 'lake',
        lat: 44.3930, lng: -110.5580,
        what: 'South-end services and campground, with a 30-ft falls on the Lewis River a few miles further south.',
        time: '30–45 min', hours: 0.6, res: 'none',
        resNote: 'Handy fuel and food stop if you are heading to the Tetons.',
    },

    /* ── Grand Teton National Park ─────────────────────────── */
    {
        id: 'jenny-lake', name: 'Jenny Lake & Hidden Falls', region: 'teton',
        lat: 43.7519, lng: -110.7226,
        what: 'The signature Teton stop — a shuttle boat across Jenny Lake to Hidden Falls and Inspiration Point beneath Cascade Canyon.',
        time: '2.5–4 hrs', hours: 3, res: 'rec',
        resNote: 'Boat shuttle is first-come and queues badly after 10am; the 7.1-mi lake loop needs no boat.',
    },
    {
        id: 'cathedral-turnout', name: 'Cathedral Group Turnout', region: 'teton',
        lat: 43.7660, lng: -110.7250,
        what: 'Roadside pullout with the cleanest head-on view of Teewinot, Grand Teton and Mount Owen together.',
        time: '15 min', hours: 0.25, res: 'none',
        resNote: 'On Teton Park Road just north of the Jenny Lake turnoff.',
    },
    {
        id: 'string-lake', name: 'String Lake', region: 'teton',
        lat: 43.7847, lng: -110.7300,
        what: 'Shallow, unusually warm lake below Mount Moran — the best swimming and paddling water in either park.',
        time: '1.5–3 hrs', hours: 2, res: 'rec',
        resNote: 'Parking fills by 9am in July and August; no permit needed for hand-launched craft on String Lake.',
    },
    {
        id: 'taggart-lake', name: 'Taggart Lake', region: 'teton',
        lat: 43.6900, lng: -110.7320,
        what: 'Gentle 3.8-mi loop through a burn scar to a moraine-dammed lake right under the Grand.',
        time: '2–2.5 hrs', hours: 2.25, res: 'none',
        resNote: 'The most rewarding short hike in the park; go early for still water.',
    },
    {
        id: 'oxbow-bend', name: 'Oxbow Bend', region: 'teton',
        lat: 43.8637, lng: -110.5490,
        what: 'Slow bend of the Snake River that mirrors Mount Moran — moose, otters and pelicans at first light.',
        time: '30 min', hours: 0.5, res: 'none',
        resNote: 'Sunrise is the whole point; by 10am the reflection is gone.',
    },
    {
        id: 'schwabacher', name: 'Schwabacher Landing', region: 'teton',
        lat: 43.7300, lng: -110.6800,
        what: 'Beaver-pond river access with the most photographed reflection of the Teton range.',
        time: '45 min', hours: 0.75, res: 'none',
        resNote: 'Short dirt access road, closed in shoulder season. Sunrise stop.',
    },
    {
        id: 'snake-river-overlook', name: 'Snake River Overlook', region: 'teton',
        lat: 43.7386, lng: -110.6300,
        what: 'The Ansel Adams viewpoint — the Snake curving away below the full range.',
        time: '20 min', hours: 0.35, res: 'none',
        resNote: 'The cottonwoods have grown since 1942; the view is still worth the pullout.',
    },
    {
        id: 'mormon-row', name: 'Mormon Row & Moulton Barn', region: 'teton',
        lat: 43.6640, lng: -110.6640,
        what: 'Homestead barns on a sage flat with the Tetons directly behind — the classic American West photograph.',
        time: '45 min', hours: 0.75, res: 'none',
        resNote: 'Bison frequently graze the row; sunrise light hits the barn face.',
    },
    {
        id: 'signal-mountain', name: 'Signal Mountain Summit Road', region: 'teton',
        lat: 43.8450, lng: -110.5410,
        what: '5-mi paved climb to a 7,720-ft overlook of Jackson Hole, the Snake River and the whole range at once.',
        time: '1 hr', hours: 1, res: 'none',
        resNote: 'No trailers or RVs. Best in late afternoon.',
    },
    {
        id: 'colter-bay', name: 'Colter Bay & Jackson Lake', region: 'teton',
        lat: 43.9020, lng: -110.6420,
        what: 'Marina, swimming beach and an easy lakeshore loop on the biggest lake in the Tetons.',
        time: '1.5–2 hrs', hours: 1.75, res: 'none',
        resNote: 'Kayak and boat rentals are walk-up; the visitor centre has a strong Indian Arts collection.',
    },
    {
        id: 'chapel-transfiguration', name: 'Chapel of the Transfiguration', region: 'teton',
        lat: 43.6600, lng: -110.7100,
        what: '1925 log chapel whose altar window frames the Cathedral Group — a two-minute stop that lands.',
        time: '20 min', hours: 0.35, res: 'none',
        resNote: 'Beside the Craig Thomas Visitor Center at Moose.',
    },
    {
        id: 'jackson-tram', name: 'Jackson Hole Aerial Tram', region: 'teton',
        lat: 43.5875, lng: -110.8280,
        what: 'Twelve-minute cable car from Teton Village to 10,450 ft on Rendezvous Mountain — waffles at the top.',
        time: '2–3 hrs', hours: 2.5, res: 'req',
        resNote: 'Ticketed; buy online for a time slot in peak summer. Outside the national park.',
    },
    {
        id: 'jackson-town', name: 'Jackson, WY', region: 'teton',
        lat: 43.4799, lng: -110.7624,
        what: 'Antler-arch town square, galleries and the Million Dollar Cowboy Bar at the south end of Jackson Hole.',
        time: '2–3 hrs', hours: 2.5, res: 'none',
        resNote: 'Dinner reservations are advisable in July and August.',
    },

    /* ── Gateway towns ─────────────────────────────────────── */
    {
        id: 'beartooth-highway', name: 'Beartooth Highway', region: 'gateway',
        lat: 45.0000, lng: -109.4300,
        what: '68-mi alpine drive out the Northeast Entrance over a 10,947-ft pass — arguably the best road in America.',
        time: 'Half day', hours: 4, res: 'none',
        resNote: 'Seasonal: typically open late May to mid-October, weather permitting.',
    },
    {
        id: 'west-yellowstone', name: 'West Yellowstone, MT', region: 'gateway',
        lat: 44.6621, lng: -111.1041,
        what: 'The main west gateway town — restaurants, fuel, the Grizzly & Wolf Discovery Center and an IMAX screen.',
        time: '1–2 hrs', hours: 1.5, res: 'none',
        resNote: 'Closest full-service town to the geyser basins.',
    },
    {
        id: 'gardiner', name: 'Gardiner, MT', region: 'gateway',
        lat: 45.0300, lng: -110.7040,
        what: 'North gateway town on the Yellowstone River — the only entrance open to cars year-round.',
        time: '1–2 hrs', hours: 1.5, res: 'none',
        resNote: 'Base for rafting trips on the Yellowstone; outfitters take same-day bookings.',
    },

    /* ── Airports & access ─────────────────────────────────── */
    {
        id: 'bzn', name: 'Bozeman — BZN', region: 'airport',
        lat: 45.7772, lng: -111.1530,
        what: 'Bozeman Yellowstone International, the busiest and closest airport to the north and west entrances.',
        time: '1h30 to Gardiner · 1h50 to West Yellowstone', hours: 2, res: 'req',
        resNote: 'Book flights and the rental car early — summer fares and car supply are both brutal here.',
    },
    {
        id: 'ida', name: 'Idaho Falls — IDA', region: 'airport',
        lat: 43.5136, lng: -112.0708,
        what: 'Small regional airport west of the park, usually the cheapest way in via Salt Lake connections.',
        time: '2h to West Yellowstone', hours: 2, res: 'req',
        resNote: 'Fewer daily flights than BZN; check the return schedule against your Day 4 departure.',
    },
    {
        id: 'slc', name: 'Salt Lake City — SLC', region: 'airport',
        lat: 40.7884, lng: -111.9779,
        what: 'Major hub five hours south — the cheapest fares and the widest car choice, at the cost of a long drive.',
        time: '4h45 to West Yellowstone · 4h30 to Jackson', hours: 4.75, res: 'req',
        resNote: 'Only worth it if you are driving up through Grand Teton and out via Jackson.',
    },
];
